### ISSUE TITLE
The app will not be updated on the official homepage.

### ISSUE THREAD

**Issue by kimyearho** [electron/apps#1005]
Hello, 
I changed the name of the app I had previously registered, inserted the PR, and the merge was successful, but the app is not updated on the official homepage. What did I do wrong? 

[#999](https://github.com/electron/apps/pull/999)

thank

**Comment by MarshallOfSound** [comment]
It looks like `electron-apps` hasn't been released in a while, heroku shows a bunch of errors in the logs, I don't have the bandwidth to look into it rn.  There is defs a deploy issue here 👍

**Comment by ulver2812** [comment]
Hi, the same for me, my PR  was merged 8 days ago but my app still doesn't appear on the electron website...

**Comment by kimyearho** [comment]
If you look at the contents of the commit, it seems that the bots do not update. There have been many such problems before ...

**Comment by BinaryMuse** [comment]
Sorry for the trouble, folks — the deploy issues have been resolved and the latest version of this repo should now be reflected on the website.
