### ISSUE TITLE
Add app

### ISSUE THREAD

**Issue by miladdavoodi** [electron/apps#1203]
I want to add an app to the app list
But I don't know how

**Comment by Sanjit1** [comment]
- Click on the fork button (as shown below) and then go to your forked repo, which will be [here](https://www.github.com/miladdavoodi/apps) **AFTER** you fork the repo.
![image](https://user-images.githubusercontent.com/26168871/65852700-cde51a80-e30b-11e9-86e8-49d4714a4231.png)
- Click on the apps directory.
![image](https://user-images.githubusercontent.com/26168871/65852815-30d6b180-e30c-11e9-9281-7599c886dacc.png)
- And make the same directory structure that you did last time:
![image](https://user-images.githubusercontent.com/26168871/65852900-8612c300-e30c-11e9-9eb3-e27419586385.png)
- Click on the create new pull request button from your fork of electron/apps
![image](https://user-images.githubusercontent.com/26168871/65852930-a5115500-e30c-11e9-8595-6d182e22e8c8.png)
- Make sure that the page looks like this (Sanjit1 will be replaced by miladdavoodi), and then click on create new pull request.
![image](https://user-images.githubusercontent.com/26168871/65852982-d0943f80-e30c-11e9-916f-a738706cf697.png)
- Name the pull request ```feat: added graphql playground ```, add some comments like what your app is about, and then click Create pull request
![image](https://user-images.githubusercontent.com/26168871/65853102-3aace480-e30d-11e9-8525-95686718f96b.png)
