### ISSUE TITLE
Build Status does not change

### ISSUE THREAD

**Issue by Sanjit1** [electron/apps#1206]
For all the pull requests I have looked at in the past few days, none of them have their checks complete because of the build status. Everyone has this in their checks:
> Build Expected — Waiting for status to be reported

Its been a couple of days, so I'm just curious what this means, and why it is showing up

**Comment by Sanjit1** [comment]
@ckerr @HashimotoYT ?

**Comment by ahkohd** [comment]
Same here. I was wondering what went wrong.

**Comment by HashimotoYT** [comment]
Fixed 🤞
