### ISSUE TITLE
No mouse events on Ubuntu Linux 19.10

### ISSUE THREAD

**Issue by micush** [electron/apps#1262]
Mouse click does not work anywhere in the app on Ubuntu Linux 19.10.

**Comment by Prithviraj001** [comment]
Do u tried any key events in that app ?

**Comment by Desires01-dev** [comment]
Resporties hQ migration certificate global ask for one person but team family Fork resporties milltary stand point view work can distribute out Time manner Steven warn Drake's me Victor Perez Garza luptcha QR barcode Google news iOS 2 Team Global London and Tortno Overstock flow Jason depuy NASA talent flow NASAowners Bloomberg Jason depuy me Victor and Android studio GitHub account G-suites G-cloud Jamie strutkz Linkin Oct cat we won't lose brand

**Comment by Desires01-dev** [comment]
Pull request through my resporties hQ migration , commit work on your problems
