### ISSUE TITLE
Error while cloning the repo

### ISSUE THREAD

**Issue by shreya-gr** [electron/apps#1360]
When I fork and clone this repo I'm getting the following errors. 
Can you please help?

Cloning into 'apps'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (31/31), done.
error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by Toinane** [comment]
Hey there, do you still have the issue?

**Comment by Toinane** [comment]
If there's no response, I'm going to close this issue from now.
Feel free to reopen it if needed 👍
