### ISSUE TITLE
This app in the list was NOT made with Electron!

### ISSUE THREAD

**Issue by phtdacosta** [electron/apps#1401]
I do not know how this app got in the list, but it seems more like a misrepresentation or someone simply trying to take advantage for some extra free advertisement. This app https://github.com/electron/apps/tree/master/apps/light-table was not made with Electron, someone please delete that from the list.

**Comment by MarshallOfSound** [comment]
I just reverified that app by downloading the latest release and it's definitely built with Electron.

![image](https://user-images.githubusercontent.com/6634592/81131339-b1dbd400-8eff-11ea-92cb-d52f24eae17a.png)
