### ISSUE TITLE
Remove broken or deprecated apps

### ISSUE THREAD

**Issue by VerteDinde** [electron/apps#1548]
Electron Apps has collected a great deal of apps over the years. However, many apps are now broken or no longer working, and thus should be removed from our directories. As part of Hacktoberfest, we'd like to clean up some of those apps.

You can find a guide for removing/disabling apps here: https://github.com/electron/apps/blob/master/contributing.md#removing-or-disabling-apps

Criteria for a Broken App:
- Link to website no longer works
- Last release was over 4 years ago
- Using a version of Electron older than 3.x

Please limit PRs to removing a **maximum of 5 apps** per PR. This will allow others to also submit Hacktoberfest PRs, and keep our maintainers from becoming overwhelmed.

**Comment by murtajaziad** [comment]
Hello, I would like to do this issue.
Can I start?

**Comment by TDDR** [comment]
Hi, I would also like to contribute to this issue. I was just wondering if all 3 of the criteria need to be met in order to qualify as broken?

**Comment by vhashimotoo** [comment]
@TDDR One criteria are enough to mark the app as delete candidate

**Comment by MrOsta** [comment]
Hey, I found some apps that don't have an electron on their package.json , should i disable it?

**Comment by Toinane** [comment]
> Hey, I found some apps that don't have an electron on their `package.json` , should i disable it?
Can you reference it here or in PR? If theses applications doesn't use Electron, they must be removed I my opinion

**Comment by tussi003** [comment]
Ano

**Comment by Toinane** [comment]
I've removed a lot of disabled application here #1740 and I'll make a new check soon, I suppose we can now close this 👍
