### ISSUE TITLE
Im facing how to run such an applcation

### ISSUE THREAD

**Issue by andybe** [electron/apps#1592]
I came along here to play with electron. 

The Documentation "readme.md" doesn't tell me how to run any kind of that application?

So i got hundred define of application ..??????

**Comment by Toinane** [comment]
Hey! If you want to learn and play with Electron, you should go to https://github.com/electron/electron
This repo is a listing of all application using Electron for the Electron website 👍

**Comment by andybe** [comment]
that isn't the point @Toinane. For example I saw a twitch application. Ok a simple url - windows application.
hm ... does' this tool help me build quick simple applications to run? 
only definations around ... 
readme.md tell me how to add my own application .l... doens't realy complain anthing.

**Comment by andybe** [comment]
Only a list of? advertising?

**Comment by andybe** [comment]
ok ... I was on the wrong roud.

**Comment by Toinane** [comment]
I don't really understand, do you want an app that help you build your own app?
Yeah this repo is just a list for advertising all app that use Electron

**Comment by andybe** [comment]
my vault.

**Comment by Toinane** [comment]
No worries 👍 
You have https://github.com/electron/electron-quick-start
and https://github.com/hokein/electron-sample-apps
maybe that can help you!

**Comment by andybe** [comment]
My first impression (idea in mind) was like ... yml define small  skeleton. Just insert one command line and it build those applications. For example Twitich is only a url (one window url application) and the rest ist up to the developer.

**Comment by Toinane** [comment]
Oh I see! the yml file is just used to add a webpage on the website like for my app here: https://www.electronjs.org/apps/colorpicker
you can see the real source code here to see an electron app isn't just a yml to build an app: https://github.com/Toinane/colorpicker
