### ISSUE TITLE
I have an error while creating pull request.

### ISSUE THREAD

**Issue by agam778** [electron/apps#1703]
Whenever I create a pull request, Semantic check fails and says :- 
`Semantic Pull Request — PR has only one non-merge commit and it's not semantic; add another com...`

Please Help!

**Comment by kherld-hussein** [comment]
Are you using VPN ?

**Comment by agam778** [comment]
No

**Comment by Toinane** [comment]
hey @agam778 you need to add "feat: " before your description in commit name. Also you can make two commit to fix that.
Otherwise, I've merged a PR that disable the semantic check on commit name.

**Comment by agam778** [comment]
Oh thanks a lot @Toinane

**Comment by Toinane** [comment]
If its now okay for you, feel free to close this issue 👍

**Comment by agam778** [comment]
Ok. Issue Closed
