### ISSUE TITLE
App not listed on electronjs.org although merge was successful

### ISSUE THREAD

**Issue by ransome1** [electron/apps#1710]
Hi there.

A couple of month ago I submitted my Electron app following the PR procedure. 

It all went well and it got merged: https://github.com/electron/apps/pull/1642

I expect the app to show up here: https://www.electronjs.org/apps

But so far this did not happen. Can anybody tell me if I did anything wrong?

Best
ransome

**Comment by Toinane** [comment]
Hey @ransome1 indeed you're right, strange! I'll investigate that! Thanks for your report
