### ISSUE TITLE
Contribution guide references wrong repository name

### ISSUE THREAD

**Issue by tkainrad** [electron/apps#1825]
[The contribution guide](https://github.com/electron/apps/blob/master/contributing.md) has the following instructions:

> ```sh
> git clone https://github.com/electron/electron-apps
> cd electron-apps
> npm install && npm run wizard
> ```
> 

However, the repository is not called `electron-apps`, but rather just `apps`. Hence, the `cd` command will not work as described.

Obviously a minor issue, thanks for giving people the chance to show their apps ;)

**Comment by Toinane** [comment]
Hey @tkainrad thank you for your issue! I'll resolve this asap!

**Comment by Toinane** [comment]
done 👍
