### ISSUE TITLE
App gets stuck during launch in MacOS

### ISSUE THREAD

**Issue by sharma94** [electron/apps#1848]
<img width="952" alt="Screenshot 2021-08-03 at 3 57 27 AM" src="https://user-images.githubusercontent.com/26078354/127933289-6d7da333-cc5b-4221-850c-2d6f02f9c6fa.png">

**Comment by sharma94** [comment]
Unable to use the app - Version 0.7.2 (0.7.2). Even unable to close the app , I need to Force quit / use quit option. 
opening Dev tool shows 7 errors, but no clue on how to resolve them and get the app back to working condition.

**Comment by Toinane** [comment]
Hey @sharma94 thanks for your issue, looks like you use an application named GraphiQL. You should report this issue to the developper of this application. This repository is just a list of application developed with Electron and not the GraphiQL one.
Here is the link to the right repo: [https://github.com/graphql/graphiql](https://github.com/graphql/graphiql)
