### ISSUE TITLE
Error when running the wizard: mkdirp is missing

### ISSUE THREAD

**Issue by warpdesign** [electron/apps#1969]
# How to reproduce?

- clone the repository
- run `npm install`
- run `npm run wizard`

# What happens?
This error is displayed:

> internal/modules/cjs/loader.js:883
>   throw err;
>   ^
> 
> 
> Error: Cannot find module 'mkdirp'
> Require stack:
> - /Users/nico/Documents/Dev/apps/wizard.js
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>     at Module.require (internal/modules/cjs/loader.js:952:19)
>     at require (internal/modules/cjs/helpers.js:88:18)
>     at Object.<anonymous> (/Users/nico/Documents/Dev/apps/wizard.js:7:16)
>     at Module._compile (internal/modules/cjs/loader.js:1063:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
>     at Module.load (internal/modules/cjs/loader.js:928:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/Users/nico/Documents/Dev/apps/wizard.js' ]
> }
> 

# What should happen?
The wizzard should be started without any error.

As a workaround, installing `mkdirp` fixes the problem:
> npm install mkdirp

**Comment by Toinane** [comment]
fixed in #1983
