### ISSUE TITLE
App submitted and merged, but not showing up on site.

### ISSUE THREAD

**Issue by JaydenDev** [electron/apps#1985]
So supposedly, my new app submitted would show on https://electronjs.org/apps within at least 24 hours. Am I misunderstanding the system, is it going to take longer than 24 hours?

**Comment by Toinane** [comment]
Hey @JaydenDev sorry for the issue. We are currently making the future next website of Electron. So I suppose the script that show new apps isn't working for now. I don't know the new website will be finished, you can see here: https://github.com/electron/electronjs.org-new
