### ISSUE TITLE
Strimio seems to not exist anymore

### ISSUE THREAD

**Issue by ropoko** [electron/apps#2037]
Both the site and the desktop application does not work anymore, I think it should be removed as the maintainer does not shared the source code and the project does not exist anymore.

**Comment by erickzhao** [comment]
Thanks for flagging this @ropoko! It seems like they've posted an announcement about this downtime on Twitter, so I'm hesitant to remove the app altogether at the moment. I think temporarily disabling the app would be a good way forward.

https://twitter.com/strimioinc/status/1542200728437116928

**Comment by ropoko** [comment]
I didn't see this, thank you

**Comment by spiral2k** [comment]
Hey all, Strimio is back again, I've [opened a PR](https://github.com/electron/apps/pull/2073) to update the information.

@erickzhao thank you for not removing Strimio
