### ISSUE TITLE
Use electron-probot to echo CI failures back to users as a comment

### ISSUE THREAD

**Issue by zeke** [electron/apps#262]
Folks don't usually notice that CI has failed, so I end up clicking into Travis, copying the error, and pasting it back as a comment on the issue so the user can fix it.

https://github.com/electron/electron-probot doesn't do anything yet, but this would be a good use for it.

**Comment by zeke** [comment]
@JasonEtco started working on a CI reporter! https://github.com/JasonEtco/ci-reporter

**Comment by JasonEtco** [comment]
He sure did! @zeke you can install it here: https://github.com/apps/ci-reporter

There is _lots_ more work to be done, and I'm not sure that its quite consistent. CircleCI's API is perfect for this use-case, Travis's is a little tougher to parse out the test steps, so its a little buggier. You're welcome to try it out for now though!
