### ISSUE TITLE
Mongo Compass: On remove a row for validate still shows Error input is not valid

### ISSUE THREAD

**Issue by Juanmabs22** [electron/apps#592]
Hey! Awesome MognoDB Team! i thinkg a foun d a littel bug.

If you use the awesome Validation tab on the collection and delete a empty row while the current Validation is not valida because the empty rule, you do not have any way to force the web check.

![mongo](https://user-images.githubusercontent.com/5569316/38157638-0891f276-3489-11e8-9404-13bd32a4d1ff.gif)

I didn't check how to fix that, if you team are busy I could found the problem, _i know it is a web app_, but i'm not sure if you agree a pull request.
If i could participate let me know.

_I'm not sure if this is the best place to put eh problem, but i didn't find a better place_

Thanks!

**Comment by zeke** [comment]
> I'm not sure if this is the best place to put eh problem

Indeed. You'll find some contact info on this page: https://www.mongodb.com/products/compass
