### ISSUE TITLE
No Latest release is being showed up on sharp-tune app

### ISSUE THREAD

**Issue by MD-AZMAL** [electron/apps#691]
I have made some updates and had a new release but it does not seem to be updated on https://electronjs.org/apps/sharp-tune

**Comment by MD-AZMAL** [comment]
though i have cleared all the releases and added just one .....

**Comment by MD-AZMAL** [comment]
@zeke any words on this ?? .... i have updated my README.md and it is not updating on https://electronjs.org/apps/sharp-tune

**Comment by MarshallOfSound** [comment]
@MD-AZMAL The README information is not dynamically pulled in at request time, it is pulled when the website is initially generated, a new release of this module will need to go out for the README information to update 👍

**Comment by Slapbox** [comment]
@MD-AZMAL I think you're all up to date now.

**Comment by MD-AZMAL** [comment]
@Slapbox yup ......i should'nt be impatient 😅
closing the issue thanks for help @MarshallOfSound @Slapbox

**Comment by moshfeu** [comment]
@Slapbox @MarshallOfSound, How much time it takes? As much as I understand, a new version is generating every 4 hours and it seems that the apps not updated after 2/3 cycles.

**Comment by Slapbox** [comment]
@moshfeu I'm not sure, but in my experience it doesn't take as long as you're seeing. Where do you get the 4 hours number?

**Comment by moshfeu** [comment]
Thanks for your reply @Slapbox . I can see it in the releases:

<img width="171" alt="screen shot 2018-12-09 at 7 01 24 pm" src="https://user-images.githubusercontent.com/3723951/49700252-f6692000-fbe4-11e8-81fd-48a47f5c4f41.png">

**Comment by Slapbox** [comment]
@moshfeu I should have asked in the last comment, what's your app too? Is it a new app, or are you referring to updating an existing one? [New apps can take a while to be added.](https://github.com/electron/apps/pull/695)

**Comment by moshfeu** [comment]
Yes, this is the repo. It takes a lot of time.
The current version in the app is 1.0.1. The next version (1.0.2) released 4 days ago.
