### ISSUE TITLE
Electron app page seems not up to date

### ISSUE THREAD

**Issue by ahmtcn123** [electron/apps#754]
I created my pull request nearly 2 days ago . I can find my app on here but i cant find it on website . Have I done something wrong ? 

App name : FridayAI

**Comment by vladimiry** [comment]
Recently closed similar issues:
- https://github.com/electron/apps/issues/395
- https://github.com/electron/apps/issues/730

**Comment by ahmtcn123** [comment]
There is a a lot of issues . So I didnt see them .

**Comment by vladimiry** [comment]
@ahmtcn123   those issues are closed already, so I'd suggest keeping this issue opened.

**Comment by ahmtcn123** [comment]
Yup. I just checked issues . Opening issue

**Comment by zeke** [comment]
Thanks for reporting. Sorry for the trouble. Investigating.

**Comment by zeke** [comment]
This was part of the problem: https://github.com/electron/apps/pull/758

But now this is happening: https://github.com/electron/apps/issues/761 -- I will look into it tomorrow.

**Comment by zeke** [comment]
Latest apps are now on the site: https://github.com/electron/electronjs.org/commit/7572b81ce6fb50559ad4e3e4762ef3c5acc0020a

The resolution to https://github.com/electron/apps/issues/761 should prevent this from happening again.

**Comment by singuerinc** [comment]
Looks like the page does not update automatically.
A day ago my app "Overlay" was added but I can't see it in the list.

**Comment by MarshallOfSound** [comment]
@singuerinc It does update automatically just not instantly.  The last automatic deploy of this package was the version before yours 17 hours ago.

https://github.com/electron/electronjs.org/pull/1385

The website will auto deploy, it just takes some time.

**Comment by singuerinc** [comment]
@MarshallOfSound It's updated, thanks.
