### ISSUE TITLE
Upgrade to newer Heroku Stack

### ISSUE THREAD

**Issue by zeke** [electron/apps#760]
Seeing this warning on deploys to Heroku:

```
Warning: You are running on a deprecated stack.
Please upgrade to the latest stack by following the instructions on:
https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack
```

Steps: https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack#upgrading-an-app

**Comment by HashimotoYT** [comment]
This repo now now use Actions for scheduled tasks. Closing 🎈
