### ISSUE TITLE
Wizard wont work

### ISSUE THREAD

**Issue by Jacobboogiebear** [electron/apps#960]
> electron-apps@1.7355.0 test C:\Users\jacob\Desktop\code\Ponger\upload-app\electron-apps
> mocha --reporter min test/human-data.js test/colors-spec.js && standard --fix

  13763 passing (5s)
  1 failing

  1) colors
       should skip entries whose icons are unreadable:

      AssertionError: expected { Object (white, black) } to have key 'black'
      + expected - actual

       [
         "black"
      -  "white"
       ]

      at Context.it (test\colors-spec.js:118:13)
      at process._tickCallback (internal/process/next_tick.js:68:7)

npm ERR! Test failed.  See above for more details.

I keep getting the above error!
My code: https://github.com/Jacobboogiebear/Ponger

**Comment by ngudbhav** [comment]
The same issue came on my PC. Running the same test on the travis CI, however, did not fail. Try directly committing to the repo.

**Comment by Sanjit1** [comment]
This is an issue from Feb, so I am curious, is it still working?

**Comment by Jacobboogiebear** [comment]
@Sanjit1 I gave up and moved on so IDK lol
